### ISSUE TITLE
Fix the sample template

### ISSUE THREAD

**Issue by nekrassov01** [nekrassov01/Pasm#7]
- [ ] Fix the sample template so that the quota limit is not exceeded
- [ ] Fix README.md
- [ ] UnitTest
- [ ] Release

#### Small incident

- With the current settings in the sample template, it is trapped by the quota limit as it is.

```yaml
Common:
  Region: ap-northeast-1
  ProfileName: default
Resource:
  NetworkAcl:
  - ResourceName: test-acl-01
    VpcId: vpc-00000000000000000
    MaxEntry: 20 # <= This threshold will be exceeded.
    FlowDirection: Ingress
    RuleNumber:
      StartNumber: 100
      Interval: 10
    AssociationSubnetId:
    - subnet-00000000000000000
    - subnet-11111111111111111
    Rules:
    - Id: 1
      ServiceKey: S3
      Region:
      - ap-northeast-1
      IpFormat:
      - IPv4
      Protocol: tcp
      FromPort: 80
      ToPort: 80
      EphemeralPort: true
    - Id: 2
      ServiceKey: S3
      Region:
      - ap-northeast-1
      IpFormat:
      - IPv4
      Protocol: tcp
      FromPort: 443
      ToPort: 443
      EphemeralPort: true
```
